
services:
  games-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: gamesapi
    container_name: gamesapi
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    environment:
      PORT: "3000"